# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# Site settings
url: 'https://secretrhythm.com'
baseurl: ''
title: 'Secret Rhythm Project'
description: 'Original Rock from Worcester, MA'
permalink: pretty
logo: "/assets/logo.gif"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Band
  url: /band/
- title: Listen
  url: /listen/
- title: Events
  url: /events/
- title: Connect
  url: https://www.facebook.com/secretrhythmproject/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Events
    output: true
    description: "Gigs & Other Events"
    feature_image: "/assets/band-photos/srp.jpg"
    feature_text: |
      # Secret Rhythm Project
